// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type DPool struct {
	UserIDs    []string `json:"userIds"`
	DepositIDs []string `json:"depositIds"`
	FunderIDs  []string `json:"funderIds"`
	FundingIDs []string `json:"fundingIds"`

	ID                           *string    `json:"id"`
	Address                      *string    `json:"address"`
	MoneyMarket                  *string    `json:"moneyMarket"`
	Stablecoin                   *string    `json:"stablecoin"`
	InterestModel                *string    `json:"interestModel"`
	Users                        []*User    //  `json:"users"`
	NumUsers                     *int       `json:"numUsers"`
	Deposits                     []*Deposit `json:"deposits"`
	NumDeposits                  *int       `json:"numDeposits"`
	NumActiveDeposits            *string    `json:"numActiveDeposits"`
	TotalActiveDeposit           *string    `json:"totalActiveDeposit"`
	TotalHistoricalDeposit       *string    `json:"totalHistoricalDeposit"`
	TotalInterestPaid            *string    `json:"totalInterestPaid"`
	UnfundedDepositAmount        *string    `json:"unfundedDepositAmount"`
	Funders                      []*Funder  //`json:"funders"`
	NumFunders                   *string    `json:"numFunders"`
	Fundings                     []*Funding `json:"fundings"`
	NumFundings                  *string    `json:"numFundings"`
	MinDepositPeriod             *float64   `json:"MinDepositPeriod"`
	MaxDepositPeriod             *float64   `json:"MaxDepositPeriod"`
	MinDepositAmount             *float64   `json:"MinDepositAmount"`
	MaxDepositAmount             *float64   `json:"MaxDepositAmount"`
	MphMintingMultiplier         *float64   `json:"mphMintingMultiplier"`
	MphDepositorRewardMultiplier *float64   `json:"mphDepositorRewardMultiplier"`
	MphFunderRewardMultiplier    *float64   `json:"mphFunderRewardMultiplier"`
	OneYearInterestRate          *float64   `json:"oneYearInterestRate"`
	Surplus                      *string    `json:"surplus"`
	MoneyMarketIncomeIndex       *string    `json:"moneyMarketIncomeIndex"`
	OracleInterestRate           *string    `json:"oracleInterestRate"`
	Proof                        *Proof     //     `json:"proof"`
}

type DPoolInput struct {
	ID                           *string  `json:"id"`
	Address                      *string  `json:"address"`
	MoneyMarket                  *string  `json:"moneyMarket"`
	Stablecoin                   *string  `json:"stablecoin"`
	InterestModel                *string  `json:"interestModel"`
	NumUsers                     *int     `json:"numUsers"`
	NumDeposits                  *int     `json:"numDeposits"`
	NumActiveDeposits            *string  `json:"numActiveDeposits"`
	TotalActiveDeposit           *string  `json:"totalActiveDeposit"`
	TotalHistoricalDeposit       *string  `json:"totalHistoricalDeposit"`
	TotalInterestPaid            *string  `json:"totalInterestPaid"`
	UnfundedDepositAmount        *string  `json:"unfundedDepositAmount"`
	NumFunders                   *string  `json:"numFunders"`
	NumFundings                  *string  `json:"numFundings"`
	MinDepositPeriod             *float64 `json:"MinDepositPeriod"`
	MaxDepositPeriod             *float64 `json:"MaxDepositPeriod"`
	MinDepositAmount             *float64 `json:"MinDepositAmount"`
	MaxDepositAmount             *float64 `json:"MaxDepositAmount"`
	MphMintingMultiplier         *float64 `json:"mphMintingMultiplier"`
	MphDepositorRewardMultiplier *float64 `json:"mphDepositorRewardMultiplier"`
	MphFunderRewardMultiplier    *float64 `json:"mphFunderRewardMultiplier"`
	OneYearInterestRate          *float64 `json:"oneYearInterestRate"`
	Surplus                      *string  `json:"surplus"`
	MoneyMarketIncomeIndex       *string  `json:"moneyMarketIncomeIndex"`
	OracleInterestRate           *string  `json:"oracleInterestRate"`
	ProofID                      *string  `json:"ProofID"`
}

type DPoolList struct {
	DPoolIDs []string `json:"dPoolIds,omitempty"`

	ID             *string  `json:"id"`
	Pools          []*DPool //`json:"pools"`
	NumPools       *int     `json:"numPools,omitempty"`
	NumUsers       *int     `json:"numUsers,omitempty"`
	NumActiveUsers *int     `json:"numActiveUsers,omitempty"`
	NumFunders     *int     `json:"numFunders,omitempty"`
	Proof          *Proof   //   `json:"proof"`
}

type DPoolListInput struct {
	ID             *string `json:"id"`
	NumPools       *int    `json:"numPools,omitempty"`
	NumUsers       *int    `json:"numUsers,omitempty"`
	NumActiveUsers *int    `json:"numActiveUsers,omitempty"`
	NumFunders     *int    `json:"numFunders,omitempty"`
	//DPoolIDs       []string `json:"dPoolIds"`
}

type Deposit struct {
	UserID  string `json:"userId"`
	DPoolID string `json:"dPoolId"`

	ID                            *string `json:"id"`
	NftID                         *string `json:"nftID"`
	User                          *User   // `json:"user"`
	Pool                          *DPool  //`json:"pool"`
	Amount                        *string `json:"amount"`
	MaturationTimestamp           *string `json:"maturationTimestamp"`
	Active                        *bool   `json:"active"`
	DepositTimestamp              *string `json:"depositTimestamp"`
	InterestEarned                *string `json:"interestEarned"`
	FundingID                     *string `json:"fundingID"`
	MintMPHAmount                 *string `json:"mintMPHAmount"`
	TakeBackMPHAmount             *string `json:"takeBackMPHAmount"`
	InitialMoneyMarketIncomeIndex *string `json:"initialMoneyMarketIncomeIndex"`
	Proof                         *Proof  //  `json:"proof"`
}

type DepositInput struct {
	ID                            *string `json:"id"`
	NftID                         *string `json:"nftID"`
	Amount                        *string `json:"amount"`
	MaturationTimestamp           *string `json:"maturationTimestamp"`
	Active                        *bool   `json:"active"`
	DepositTimestamp              *string `json:"depositTimestamp"`
	InterestEarned                *string `json:"interestEarned"`
	FundingID                     *string `json:"fundingID"`
	MintMPHAmount                 *string `json:"mintMPHAmount"`
	TakeBackMPHAmount             *string `json:"takeBackMPHAmount"`
	InitialMoneyMarketIncomeIndex *string `json:"initialMoneyMarketIncomeIndex"`
	ProofID                       *string `json:"ProofID"`
}

type Funder struct {
	DPoolIDs               []string `json:"dPoolIds"`
	FundingIDs             []string `json:"fundingIds"`
	FunderTotalInterestIDs []string `json:"funderTotalInterestIds"`

	ID                  *string                `json:"id"`
	Address             *string                `json:"address"`
	Pools               []*DPool               //             `json:"pools"`
	NumPools            *string                `json:"numPools"`
	Fundings            []*Funding             //           `json:"fundings"`
	NumFundings         *string                `json:"numFundings"`
	TotalMPHEarned      *string                `json:"totalMPHEarned"`
	TotalInterestByPool []*FunderTotalInterest `json:"totalInterestByPool"`
	Proof               *Proof                 //                 `json:"proof"`
}

type FunderInput struct {
	ID             *string `json:"id"`
	Address        *string `json:"address"`
	NumPools       *string `json:"numPools"`
	NumFundings    *string `json:"numFundings"`
	TotalMPHEarned *string `json:"totalMPHEarned"`
	ProofID        *string `json:"ProofID"`
}

type FunderTotalInterest struct {
	FunderID string `json:"funderId"`
	DPoolID  string `json:"dPoolId"`

	ID                               *string `json:"id"`
	Funder                           *Funder `json:"funder"`
	Pool                             *DPool  //`json:"pool"`
	TotalDeficitFunded               *string `json:"totalDeficitFunded"`
	TotalHistoricalDeficitFunded     *string `json:"totalHistoricalDeficitFunded"`
	TotalInterestEarned              *string `json:"totalInterestEarned"`
	TotalHistoricalInterestEarned    *string `json:"totalHistoricalInterestEarned"`
	TotalRecordedFundedDepositAmount *string `json:"totalRecordedFundedDepositAmount"`
	Proof                            *Proof  //  `json:"proof"`
}

type FunderTotalInterestInput struct {
	ID                               *string `json:"id"`
	TotalDeficitFunded               *string `json:"totalDeficitFunded"`
	TotalHistoricalDeficitFunded     *string `json:"totalHistoricalDeficitFunded"`
	TotalInterestEarned              *string `json:"totalInterestEarned"`
	TotalHistoricalInterestEarned    *string `json:"totalHistoricalInterestEarned"`
	TotalRecordedFundedDepositAmount *string `json:"totalRecordedFundedDepositAmount"`
	ProofID                          *string `json:"ProofID"`
}

type Funding struct {
	FunderID string `json:"funderId"`
	DPoolID  string `json:"dPoolId"`

	ID                             *string `json:"id"`
	NftID                          *string `json:"nftID"`
	Funder                         *Funder `json:"funder"`
	Pool                           *DPool  //`json:"pool"`
	FromDepositID                  *string `json:"fromDepositID"`
	ToDepositID                    *string `json:"toDepositID"`
	Active                         *bool   `json:"active"`
	RecordedFundedDepositAmount    *string `json:"recordedFundedDepositAmount"`
	RecordedMoneyMarketIncomeIndex *string `json:"recordedMoneyMarketIncomeIndex"`
	InitialFundedDepositAmount     *string `json:"initialFundedDepositAmount"`
	FundedDeficitAmount            *string `json:"fundedDeficitAmount"`
	TotalInterestEarned            *string `json:"totalInterestEarned"`
	MintMPHAmount                  *string `json:"mintMPHAmount"`
	Proof                          *Proof  //  `json:"proof"`
}

type FundingInput struct {
	ID                             *string `json:"id"`
	NftID                          *string `json:"nftID"`
	FromDepositID                  *string `json:"fromDepositID"`
	ToDepositID                    *string `json:"toDepositID"`
	Active                         *bool   `json:"active"`
	RecordedFundedDepositAmount    *string `json:"recordedFundedDepositAmount"`
	RecordedMoneyMarketIncomeIndex *string `json:"recordedMoneyMarketIncomeIndex"`
	InitialFundedDepositAmount     *string `json:"initialFundedDepositAmount"`
	FundedDeficitAmount            *string `json:"fundedDeficitAmount"`
	TotalInterestEarned            *string `json:"totalInterestEarned"`
	MintMPHAmount                  *string `json:"mintMPHAmount"`
	ProofID                        *string `json:"ProofID"`
}

type Mph struct {
	ID                    *string `json:"id"`
	TotalSupply           *string `json:"totalSupply"`
	TotalStakedMPHBalance *string `json:"totalStakedMPHBalance"`
	TotalHistoricalReward *string `json:"totalHistoricalReward"`
	RewardPerSecond       *string `json:"rewardPerSecond"`
	RewardPerMPHPerSecond *string `json:"rewardPerMPHPerSecond"`
	Proof                 *Proof  //  `json:"proof"`
}

type MPHHolder struct {
	ID                    *string `json:"id"`
	Address               *string `json:"address"`
	MphBalance            *string `json:"mphBalance"`
	StakedMPHBalance      *string `json:"stakedMPHBalance"`
	TotalHistoricalReward *string `json:"totalHistoricalReward"`
	Proof                 *Proof  //  `json:"proof"`
}

type MPHHolderInput struct {
	ID                    *string `json:"id"`
	Address               *string `json:"address"`
	MphBalance            *string `json:"mphBalance"`
	StakedMPHBalance      *string `json:"stakedMPHBalance"`
	TotalHistoricalReward *string `json:"totalHistoricalReward"`
	ProofID               *string `json:"ProofID"`
}

type MPHInput struct {
	ID                    *string `json:"id"`
	TotalSupply           *string `json:"totalSupply"`
	TotalStakedMPHBalance *string `json:"totalStakedMPHBalance"`
	TotalHistoricalReward *string `json:"totalHistoricalReward"`
	RewardPerSecond       *string `json:"rewardPerSecond"`
	RewardPerMPHPerSecond *string `json:"rewardPerMPHPerSecond"`
	ProofID               *string `json:"ProofID"`
}

type Proof struct {
	Root  *string `json:"root"`
	Proof *string `json:"proof"`
}

type User struct {
	DPoolIDs            []string `json:"dPoolIds"`
	DepositIDs          []string `json:"depositIds"`
	UserTotalDepositIDs []string `json:"userTotalDepositIds"`

	ID                 *string             `json:"id"`
	Address            *string             `json:"address"`
	Pools              []*DPool            //          `json:"pools"`
	NumPools           *string             `json:"numPools"`
	Deposits           []*Deposit          //        `json:"deposits"`
	NumDeposits        *string             `json:"numDeposits"`
	NumActiveDeposits  *string             `json:"numActiveDeposits"`
	TotalDepositByPool []*UserTotalDeposit `json:"totalDepositByPool"`
	TotalMPHEarned     *string             `json:"totalMPHEarned"`
	TotalMPHPaidBack   *string             `json:"totalMPHPaidBack"`
	Proof              *Proof              //              `json:"proof"`
}

type UserInput struct {
	ID                *string `json:"id"`
	Address           *string `json:"address"`
	NumPools          *string `json:"numPools"`
	NumDeposits       *string `json:"numDeposits"`
	NumActiveDeposits *string `json:"numActiveDeposits"`
	TotalMPHEarned    *string `json:"totalMPHEarned"`
	TotalMPHPaidBack  *string `json:"totalMPHPaidBack"`
	ProofID           *string `json:"ProofID"`
}

type UserTotalDeposit struct {
	UserID  string `json:"userId"`
	DPoolID string `json:"dPoolId"`

	ID                            *string `json:"id"`
	User                          *User   // `json:"user"`
	Pool                          *DPool  //`json:"pool"`
	TotalActiveDeposit            *string `json:"totalActiveDeposit"`
	TotalHistoricalDeposit        *string `json:"totalHistoricalDeposit"`
	TotalInterestEarned           *string `json:"totalInterestEarned"`
	TotalHistoricalInterestEarned *string `json:"totalHistoricalInterestEarned"`
	Proof                         *Proof  //  `json:"proof"`
}

type UserTotalDepositInput struct {
	ID                            *string `json:"id"`
	TotalActiveDeposit            *string `json:"totalActiveDeposit"`
	TotalHistoricalDeposit        *string `json:"totalHistoricalDeposit"`
	TotalInterestEarned           *string `json:"totalInterestEarned"`
	TotalHistoricalInterestEarned *string `json:"totalHistoricalInterestEarned"`
	ProofID                       *string `json:"ProofID"`
}
