package dataloader

import (
  //cache "github.com/patrickmn/go-cache"
  models "github.com/proxima-one/binance-chain-subgraph/pkg/models"
  json "github.com/json-iterator/go"
  proxima "github.com/proxima-one/proxima-db-client-go"
)

type Dataloader struct {
	db *proxima.ProximaDB
}

func NewDataloader(db *proxima.ProximaDB) (*Dataloader, error) {
	return &Dataloader{
		db: db
	}, nil
}



//Generated by the dataloader itself
///dataloaders for proxima
func (d *Dataloader) LoadProximaBlockStats(args map[string]interface{}) (*models.ProximaBlockStats, error) {
    value := models.BlockStats{}
    json.Unmarshal(result.GetValue(), &value)
    proof := GenerateProof(result.GetProof())
    blockStats := &models.ProximaBlockStats{BlockStats: &value, Proof: &proof}
    return blockStats, nil
    //updateBlockStats()
}
